### PR TITLE
Add workspace loading to filter job (Closes #15) [semver:patch]

### LINKED ISSUE #15: Support loading a workspace
## Describe Request:
We're trying to dynamically generate the continuation config in addition to using the path filtering orb, but because the path filtering orb doesn't use workspaces, we can't build the config in one job, and then have the path filtering job use that same config via workspaces

## Examples:

Ideally we can have a job that has this step:
```
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/dynamic-config.yml
```

And the orb will load the workspace, allowing us to point the new dynamically generated config to be the one used in continiuation.

### PR DESCRIPTION
**Pull request by JamieSinn**
Add a conditional to allow loading and attaching a workspace to allow using auto-generated configs.

### CODE REVIEW

**Comment by felicianotech** [comment]
Instead of having both `enable_workspaces` and `workspace_path` here, I think we could get away with just the latter. If the path string is empty, that means workspaces shouldn't be enabled. Otherwise it is.

**Comment by JamieSinn** [comment]
@felicianotech - Updated - lemme know if there's anything else you'd like.

**Review by stig — APPROVED** [review]
LGTM.

**Comment by JamieSinn** [comment]
@stig Any update on this being merged/released in a new orb?

**Review by gmemstr — APPROVED** [review]

**Pull request merged**
